### ISSUE TITLE
Firefox extension never connects to my instance

### ISSUE THREAD

**Issue by IkariDevGIT** [goniszewski/grimoire-web-extension#2]
it always just says Grimoire API is not reachable!
The api IS reachable tho

**Comment by goniszewski** [comment]
Hello @IkariDevGIT! Did you add the URL with `/api` at the end? If so, please also check if `curl -o - -I  <YOUR_INSTANCE_URL>/api/health` responds with code `200` (from the same host as the browser).

**Comment by IkariDevGIT** [comment]
@goniszewski yep already tested. I disabled my container for now because it's eating up a bit of ram, at it's current state grimoire itself seems really buggy but i like where this project is going.

**Comment by goniszewski** [comment]
On Firefox, you should also be asked to allow the extension to connect to all hosts. Did you allow it?
Another thing that comes to mind is to not place the '/' at the end of the URL.

**Comment by IkariDevGIT** [comment]
I tried with and without the /, i also allowed it to connect to all hosts.

**Comment by goniszewski** [comment]
That's interesting. Would you be able to check the logs of the extension? In Firefox, you can paste `about:debugging#/runtime/this-firefox` into an address bar, click _Inspect_ on the extension, and check the Console tab for logs and the Network tab for additional context.

It would be very helpful if there's some more data here that could help me understand this issue.

**Comment by NovaCyntax** [comment]
`[DEBUG] popup.onMount - init [popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
[DEBUG] chrome.tabs.query - active tab: {"url":"http://my-grimoire-instance:5173/","title":"Grimoire","icon_url":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsSAAALEgHS3X78AAAgAElEQVR4Xuy9B3yc1ZU2fqb3rhn13mxJlovcsI0bxfTQIYSQQDaQsAlJNtm0zZf4Y7ObRkiWkAJJFhIIzRgMGNMNNrhg425LltV7m9Foep/5P+cdj6wuWTZZ8u3/7upnIs285d5zT3nOc84V0f8//lfPgOh/y9s/99xNEm1vhjSmsEgkIYdUHJVKFRqxOBaRJxKyeDSuikVjQ6HovkFLbOPGjdH/LfPy/5QAPPTQVxVlUalGpFBr+h12c3ObM8/tD+UGwlFTIpFQhsMxeSgal0aiMVk0GpUFgmGpQi6PyeXSiEwqjsghFnKZLCIWUVApl7pUamlXUaahLSvNZlfGIt4Bcdx307/8KohJS/y/IiD/0ALw7sbPK90Wm7m3eyi3rWtwXp/TkzvoCthc3mCGxxdO94ci+lA4pg1FogosmCQRJ3EiEReFo4TFTyjjCRKNmIDEiP+RkIhFMZ1WNphuVnZpVfJ+o17Za9Kq+61mdXd2hvlYcV5aa6bSaa+5+9EAvvcPKxD/cALw/u++a6pvHyho6RuqHnD4i9t7XUW9Tm+J1xeyYadrotG4IhaLK6OxuBz/iqKxBMXi8TEbVkwikuF34ik2coIk4hjJ8DGpRByWSsVBiUQcUsmlfo1a5kgzaprz0/XNtjRdc1F22uGCPH3Lnj6tHeZj7M0+0criH0IA3vjFtzQ9bldBfevgilMdjvktXYPVHn84MyDs8KgmHImpw9GYKBbDXCck2NZTLSw+khBBAPDqI/f/uGVK4HOsIs5s7gRBhUAo5FIJyWWSgEIm9SkVUq9GKev…
[popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
[DEBUG] onMount - loaded storage data: {"token":false,"configuration":{"grimoireApiUrl":"http://my-grimoire-instance:5173/api","saveScreenshot":false}} [popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
[DEBUG] background.messages.validate-grimoire-api-url - Validating Grimoire API URL: {"grimoireApiUrl":"http://my-grimoire-instance:5173/api"} [index.js:1:4394](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/static/background/index.js)
Content-Security-Policy: Upgrading insecure request ‘http://my-grimoire-instance:5173/api/health’ to use ‘https’
[ERROR] background.messages.validate-grimoire-api-url - Error validating Grimoire API URL: "NetworkError when attempting to fetch resource." [index.js:1:4308](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/static/background/index.js)
    error moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/static/background/index.js:1
    o moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/static/background/index.js:1
    ["8x2FD"]</< moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/static/background/index.js:1
[DEBUG] onMount - Grimoire API status: "not reachable" [popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
[DEBUG] onMount - contentScriptResponse: {"html":"<head>\n\t\t<meta charset=\"utf-8\">\n\t\t<link rel=\"icon\" href=\"http://my-grimoire-instance:5173/favicon.png\">\n\t\t<meta name=\"viewport\" content=\"width=device-width\">\n\t\t\n\t\t<link href=\"./_app/immutable/assets/0.QShtHqLF.css\" rel=\"stylesheet\">\n\t\t<link href=\"./_app/immutable/assets/show-toast.i6Zha27y.css\" rel=\"stylesheet\">\n\t\t<link href=\"./_app/immutable/assets/Select.5s-Ten9C.css\" rel=\"stylesheet\">\n\t<link rel=\"modulepreload\" as=\"script\" crossorigin=\"\" href=\"http://my-grimoire-instance:5173/_app/immutable/nodes/0.OmGrSi5B.js\"><link rel=\"modulepreload\" as=\"script\" crossorigin=\"\" href=\"http://my-grimoire-instance:5173/_app/immutable/chunks/scheduler.M7jQtDAU.js\"><link rel=\"modulepreload\" as=\"script\" crossorigin=\"\" href=\"http://my-grimoire-instance:5173/_app/immutable/chunks/index.cgcaHhiv.js\"><link rel=\"modulepreload\" as=\"script\" crossorigin=\"\" href=\"http://my-grimoire-instance:5173/_app/immutable/chunks/spread.GNysL_7k.js\"><link rel=\"modulepreloa…
[popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
[DEBUG] onMount - validationInterval: "initiating" [popup.965c99b2.js:7:14388](moz-extension://b298463f-afa2-4035-af67-4bb83c167c4e/popup.965c99b2.js)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'”
Source: addBookmarkModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'”
Source: addBookmarkModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'”
Source: addBookmarkModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'”
Source: addBookmarkModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'”
Source: addCategoryModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'”
Source: addCategoryModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self' 'wasm-unsafe-eval'”
Source: addCategoryModal.showModal() [srcdoc](about:srcdoc)
Content-Security-Policy: The page’s settings blocked an event handler (script-src-attr) from being executed because it violates the following directive: “script-src 'self'”
Source: addCategoryModal.showModal()`

I have the same issue here. I use a Chromium browser on Android, and the companion connects fine. On desktop however, I use Firefox. The Firefox extension appears to try and change it from "http" to "https" automatically, and my grimoire instance is not behind https. Not sure if the Chromium extension does the same thing or not, but it works for my instance. I would really like to use this project as it fits my workflow better than Linkding or similar alternatives.
